### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by ZachOrr**
! DON'T MERGE PLEASE !

Working on rewriting this app to be on-par with the Android app (to start). Some of the design is really Android-y, and I'm willing to work on making it better on the platform. However, I'm missing quite a few things that would be nice to have that I'm missing (what fonts are being used, sizes, spacing, icons that are the appropriate size). There's still lots that needs to be done. Large changes from what's currently on master includes

+ Removes Map view from Events view (and map-related dependicies)
+ Decouples Core Data code from Tab Bar View Controller
+ Removes AFNetworking
+ Simplifies event sorting logic by the addition of OrderedDictionary

Off the top of my head, there's a handful of things that would be nice to do in the codebase, but not needed to ship

- Handle failed network requests in TBAImporter
- Figure out good abstraction between Refresh, Year Select, and Sliding Tabs
- Work on "TBAKit", an Obj-C wrapper around TBA API

Here's some screenshots of what there is so far - working on populating other views as I go

ios simulator screen shot apr 30 2015 8 57 45 pm

ios simulator screen shot apr 30 2015 8 57 48 pm

ios simulator screen shot apr 30 2015 8 57 54 pm

ios simulator screen shot apr 30 2015 8 58 01 pm

ios simulator screen shot apr 30 2015 8 58 03 pm

### CODE REVIEW

**Comment by fangeugene** [comment]
This is awesome! Thanks for kicking this off again.

I don't know how much of your database/API/syncing stuff is implemented, but you should talk to Phil and Nathan about the design of it. The Android team is planning a pretty big rewrite of how database accessing works in the app after what they've learned this past season and they may be able to provide some insight even though the platforms may be different.

**Comment by ZachOrr** [comment]
Modified the teams page. I'm trying to kill off the sliding tab bars in the iOS app. I also have a hard time believing people actually want to scroll through groups of teams, or there's any sort of team discovery that involves browsing a long list. A basic list with a search is probably more effective for this page

ios simulator screen shot may 2 2015 12 27 38 pm
ios simulator screen shot may 2 2015 12 27 42 pm

**Comment by ZachOrr** [comment]
Leaving myself a note, which we're talking about the teams page - I think exposing the search bar initially makes this page significantly more approachable (and useful). And in an effort not to have a search bar with a pull to refresh, I've left the refresh control as a bar button item.

We could make the search the bar button item, and have a pull to refresh, but we lose the initial activity indicator showing that we're loading the teams. This might be fixable with a no data state, but I'm not sure it's worth the effort just to have a pull to refresh. The refresh button is obvious enough. (http://ux.stackexchange.com/a/17931)

**Comment by fangeugene** [comment]
I think your reasoning makes sense. Make sure searching for stuff with special characters (like Überbots) works even if "U" is typed.

**Comment by ZachOrr** [comment]
In the search on the website, you see a Ü, but not on their team page

http://www.thebluealliance.com/team/1124

Looks like we don't actually have a Ü in the team's model either 
img_4004

I can run through at a later date and check to see how we're handling unicode and whatnot

**Comment by fangeugene** [comment]
Actually it looks like they changed their team name.
http://www.usfirst.org/whats-going-on/team/302533/?ProgramCode=FRC

**Comment by phil-lopreiato** [comment]
@ZachOrr later this week, I'm going to start a new planning document for the android app data storage rewrite. It'll probably be heavy on the [Observer Pattern](https://en.wikipedia.org/wiki/Observer_pattern) to handle background things (because [AsyncTask is bad](http://stablekernel.com/blog/replace-asynctask-asynctaskloader-rx-observable-rxjava-android-patterns/)). We'll keep you in the loop.

**Comment by ZachOrr** [comment]
Changed a lot related to the models, which took a while to do... But the districts screen(s) are also coming along

ios simulator screen shot jun 7 2015 11 23 11 am
ios simulator screen shot jun 7 2015 11 23 12 am

**Comment by fangeugene** [comment]
Nice! Lookin' sweet.

**Comment by ZachOrr** [comment]
Working on a handful of things - teams/events view, new year select interface
ios simulator screen shot jun 20 2015 1 45 25 pm
ios simulator screen shot jun 20 2015 2 23 37 pm

**Comment by ZachOrr** [comment]
Lots of work with refresh states and showing data and whatnot (examples below)
ios simulator screen shot jul 12 2015 11 00 44 am
ios simulator screen shot jul 12 2015 11 01 16 am

**Comment by ZachOrr** [comment]
Media for a team is in it's own tab now, like Android. It looks cleaner that way. Gotta take another pass at the design, but we'll get there.

ios simulator screen shot aug 22 2015 2 56 01 pm

**Comment by brandondean** [comment]
To reflect that this is the direction we are going I'm going to merge this in and make master what we should be working off of.

Thanks for the sweet work, @ZachOrr. Totally :nail_care:'d it! :beers:

**Comment by phil-lopreiato** [comment]
Woooo! Nice job @ZachOrr

**Comment by ZachOrr** [comment]
Thanks everyone! I'm super excited to get this polished up and ready for users.

**Pull request merged**
