### PR TITLE
App Icons

### PR DESCRIPTION
**Pull request by brandondean**
Nothing really special here. Using the blue that's in the app with the lamp logo. #22 
screen shot 2015-11-23 at 23 43 43 pm

### CODE REVIEW

**Comment by nwalters512** [comment]
If you want something that could fit in better with Apple's flat icons, you could use the flattened lamp from the Android app: https://github.com/the-blue-alliance/the-blue-alliance-logo/blob/master/android/svg/ic_launcher_blue.svg

**Comment by brandondean** [comment]
@nwalters512 I would prefer a flat logo like Android, but I didn't want to go against branding. We shall see what happens in the-blue-alliance/the-blue-alliance#1285

**Comment by synth3tk** [comment]
For the [Windows app](https://github.com/the-blue-alliance/the-blue-alliance-windows/tree/mvp/TheBlueAlliance/Assets), I've also simply adapted the Android icons, although I had to scale them up and down (thank goodness for SVG).

I think that's the general direction we're going in for the short-term until that issue is resolved.

**Comment by ZachOrr** [comment]
Merging this for now so we can have an app icon

**Pull request merged**
