### PR TITLE
Show play button for matches that have videos.

### LINKED ISSUE #56: Add Play button to match cells that have videos

### PR DESCRIPTION
**Pull request by brandondean**
Puts the match label and play button in their own vertical stack view, and
hides the play stack view if there isn't a video available for the match.

Closes #56
simulator screen shot may 1 2016 18 20 49 pm

### CODE REVIEW

**Comment by ZachOrr** [comment]
Is there any way we could grab the same play button the Android app uses?

**Comment by brandondean** [comment]
simulator screen shot may 1 2016 19 07 09 pm

**Comment by ZachOrr** [comment]
Made a few changes to make sure that the play button and two lines of text will always fit properly

**Comment by phil-lopreiato** [comment]
Heads up, the Android app gets most of its icons here (some are a little outdated/less material-ey): https://design.google.com/icons/

**Pull request merged**
